-- ============================================
-- 팀원용 스키마 생성 스크립트
-- ============================================

-- ============================================
-- 1단계: 테이블 생성
-- ============================================
CREATE TABLE IF NOT EXISTS `AGENCY` (
	`AGENCY_NO`	BIGINT	NOT NULL,
	`AGENCY_NAME`	VARCHAR(30)	NULL,
	`AGENCY_CODE`	VARCHAR(6)	NULL,
	`AGENCY_LEAVE`	INT	NULL	DEFAULT 15
);

CREATE TABLE IF NOT EXISTS `MEMBER` (
	`MEMBER_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NULL,
	`MEMBER_NAME`	VARCHAR(20)	NOT NULL,
	`MEMBER_PASSWORD`	VARCHAR(100)	NOT NULL,
	`MEMBER_EMAIL`	VARCHAR(50)	NOT NULL,
	`MEMBER_PHONE`	VARCHAR(15)	NOT NULL,
	`MEMBER_ADDRESS`	VARCHAR(100)	NULL,
	`MEMBER_STATUS`	VARCHAR(20)	NOT NULL	COMMENT '활성 / 휴면 (ACTIVE /  BLOCKED)',
	`MEMBER_PROFILE_IMAGE`	VARCHAR(100)	NULL,
	`MEMBER_PROFILE_BANNER_IMAGE`	VARCHAR(100)	NULL,
	`MEMBER_ROLE`	VARCHAR(100)	NOT NULL	COMMENT '웹툰 작가 / 웹소설 작가 / 어시스트 - 채색 / 어시스트 - 조명 / 어시스트 - 배경 / 어시스트 - 선화 / 어시스트- 기타 / 에이전시 관리자 / 담당자',
	`MEMBER_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`MEMBER_UPDATED_AT`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `PROJECT` (
	`PROJECT_NO`	BIGINT	NOT NULL,
	`PROJECT_NAME`	VARCHAR(100)	NOT NULL,
	`PROJECT_STATUS`	VARCHAR(100)	NOT NULL	DEFAULT '연재'	COMMENT '연재 / 휴재 / 완결',
	`PROJECT_COLOR`	VARCHAR(50)	NOT NULL	DEFAULT '기본색',
	`PROJECT_GENRE`	VARCHAR(50)	NULL,
	`PROJECT_CYCLE`	INT	NULL,
	`PLATFORM`	VARCHAR(100)	NULL,
	`THUMBNAIL_FILE`	VARCHAR(500)	NULL,
	`PROJECT_STARTED_AT`	DATETIME	NULL
);

CREATE TABLE IF NOT EXISTS `HEALTH_SURVEY` (
	`HEALTH_SURVEY_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_PERIOD`	INT	NULL	DEFAULT 15,
	`HEALTH_SURVEY_CYCLE`	INT	NULL	DEFAULT 30,
	`HEALTH_SURVEY_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`HEALTH_SURVEY_UPDATED_AT`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `NOTIFICATION` (
	`NOTIFICATION_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`NOTIFICATION_NAME`	VARCHAR(30)	NULL,
	`NOTIFICATION_TEXT`	VARCHAR(260)	NULL,
	`NOTIFICATION_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`NOTIFICATION_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT 'Y / N',
	`NOTIFICATION_TYPE`	VARCHAR(30)	NULL
);

CREATE TABLE IF NOT EXISTS `LEAVE_BALANCE` (
	`LEAVE_BALANCE_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`LEAVE_TYPE`	VARCHAR(20)	NOT NULL	DEFAULT 'ANNUAL'	COMMENT '연차 / 대체휴무 / 특별휴가',
	`LEAVE_BALANCE_TOTAL_DAYS`	INT	NOT NULL,
	`LEAVE_BALANCE_USED_DAYS`	INT	NULL	DEFAULT 0,
	`LEAVE_BALANCE_REMAIN_DAYS`	DOUBLE	NULL,
	`LEAVE_BALANCE_YEAR`	VARCHAR(4)	NOT NULL,
	`LEAVE_BALANCE_UPDATED_AT`	DATE	NULL
);

CREATE TABLE IF NOT EXISTS `ATTENDANCE_REQUEST` (
	`ATTENDANCE_REQUEST_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`ATTENDANCE_REQUEST_TYPE`	VARCHAR(20)	NOT NULL	COMMENT '연차 / 병가 / 워케이션 / 재택 / 휴재 / 반차 / 반반차',
	`ATTENDANCE_REQUEST_START_DATE`	DATETIME	NOT NULL,
	`ATTENDANCE_REQUEST_END_DATE`	DATETIME	NOT NULL,
	`ATTENDANCE_REQUEST_USING_DAYS`	INT	NOT NULL,
	`ATTENDANCE_REQUEST_REASON`	VARCHAR(255)	NULL,
	`WORKCATION_LOCATION`	VARCHAR(100)	NULL	COMMENT '워케이션 신청 시에만 작성',
	`MEDICAL_FILE_URL`	VARCHAR(500)	NOT NULL,
	`ATTENDANCE_REQUEST_STATUS`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT '신청 / 승인 / 반려 / 취소',
	`ATTENDANCE_REQUEST_REJECT_REASON`	VARCHAR(200)	NULL,
	`ATTENDANCE_REQUEST_CREATED_AT`	DATETIME	NOT NULL,
	`ATTENDANCE_REQUEST_UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE IF NOT EXISTS `ATTENDANCE` (
	`ATTENDANCE_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NOT NULL,
	`ATTENDANCE_TYPE`	VARCHAR(10)	NOT NULL	COMMENT '출근, 퇴근',
	`ATTENDANCE_TIME`	DATETIME	NOT NULL
);

CREATE TABLE IF NOT EXISTS `PROJECT_MEMBER` (
	`PROJECT_MEMBER_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`PROJECT_NO`	BIGINT	NOT NULL,
	`PROJECT_MEMBER_ROLE`	VARCHAR(50)	NOT NULL	DEFAULT 'MEMBER'	COMMENT 'LEADER / 메인작가/ 어시'
);

CREATE TABLE IF NOT EXISTS `KANBAN_BOARD` (
	`KANBAN_BOARD_NO`	BIGINT	NOT NULL,
	`PROJECT_NO`	BIGINT	NOT NULL,
	`KANBAN_BOARD_NAME`	VARCHAR(100)	NULL,
	`KANBAN_BOARD_ORDER`	INT	NOT NULL,
	`KANBAN_BOARD_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT 'Y / N'
);

CREATE TABLE IF NOT EXISTS `KANBAN_CARD` (
	`KANBAN_CARD_NO`	BIGINT	NOT NULL,
	`BOARD_NO`	BIGINT	NOT NULL,
	`PROJECT_MEMBER_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_NAME`	VARCHAR(50)	NOT NULL,
	`KANBAN_CARD_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT 'N'	COMMENT '완료/미완료 체크(Y/N/D)',
	`KANBAN_CARD_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`KANBAN_CARD_UPDATED_AT`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`KANBAN_CARD_STARTED_AT`	DATE	NULL,
	`KANBAN_CARD_ENDED_AT`	DATE	NULL,
	`KANBAN_CARD_DESCRIPTION`	VARCHAR(255)	NULL
);

CREATE TABLE IF NOT EXISTS `COMMENT` (
	`COMMENT_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`COMMENT_CONTENT`	VARCHAR(1000)	NULL,
	`COMMENT_STATUS`	VARCHAR(10)	NOT NULL	DEFAULT 'ACTIVE'	COMMENT 'ACTIVE / BLOCKED',
	`COMMENT_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `MEMO` (
	`MEMO_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`MEMO_NAME`	VARCHAR(30)	NOT NULL,
	`MEMO_TEXT`	VARCHAR(255)	NULL,
	`MEMO_CREATED_AT`	DATETIME	NOT NULL,
	`CALENDAR_MEMO_DATE` DATETIME,
	`MEMO_UPDATED_AT`	DATETIME	NULL,
	`MEMO_TYPE`	VARCHAR(12)	NULL	COMMENT '개인메모/캘린더메모'
);

CREATE TABLE IF NOT EXISTS `HEALTH_SURVEY_QUESTION` (
	`HEALTH_SURVEY_QUESTION_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_ORDER`	INT	NULL,
	`HEALTH_SURVEY_QUESTION_CONTENT`	VARCHAR(1000)	NULL,
	`HEALTH_SURVEY_QUESTION_TYPE`	VARCHAR(20)	NULL,
	`HEALTH_SURVEY_QUESTION_MIN_SCORE`	INT	NULL,
	`HEALTH_SURVEY_QUESTION_MAX_SCORE`	INT	NULL,
	`HEALTH_SURVEY_QUESTION_CREATED_AT`	DATETIME	NOT NULL,
	`HEALTH_SURVEY_QUESTION_UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE IF NOT EXISTS `HEALTH_SURVEY_RESPONSE_ITEM` (
	`HEALTH_SURVEY_RESPONSE_ITEM_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_QUESTION_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_QUESTION_ITEM_ANSWER_SCORE`	INT	NOT NULL	COMMENT '0 / 1 / 2 / 3',
	`HEALTH_SURVEY_QUESTION_ITEM_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`MEMBER_NO`	BIGINT	NOT NULL
);

CREATE TABLE IF NOT EXISTS `DAILY_HEALTH_CHECK` (
	`HEALTH_CHECK_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`HEALTH_CONDITION`	VARCHAR(20)	NULL,
	`SLEEP_HOURS`	INT	NULL,
	`DISCOMFORT_LEVEL`	INT	NULL,
	`HEALTH_CHECK_NOTES`	VARCHAR(1000)	NULL,
	`HEALTH_CHECK_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `LEAVE_HISTORY` (
	`LEAVE_HISTORY_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`LEAVE_HISTORY_DATE`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP,
	`LEAVE_HISTORY_TYPE`	VARCHAR(30)	NOT NULL	COMMENT '경력 인정/ 징계 / 포상',
	`LEAVE_HISTORY_REASON`	VARCHAR(1000)	NULL,
	`LEAVE_HISTORY_AMOUNT`	INT	NOT NULL
);

CREATE TABLE IF NOT EXISTS `NEW_REQUEST` (
	`NEW_REQUEST_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`NEW_REQUEST_DATE`	DATETIME	NULL,
	`NEW_REQUEST_STATUS`	VARCHAR(10)	NULL	COMMENT '승인/대기/거절'
);

CREATE TABLE IF NOT EXISTS `MANAGER` (
	`MANAGER_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL
);

CREATE TABLE IF NOT EXISTS `ARTIST_ASSIGNMENT` (
	`ARTIST_ASSIGNMENT_NO`	BIGINT	NOT NULL,
	`ARTIST_MEMBER_NO`	BIGINT	NOT NULL,
	`MANAGER_NO`	BIGINT	NOT NULL
);

CREATE TABLE IF NOT EXISTS `PROJECT_LEAVE_REQUEST` (
	`PROJECT_LEAVE_REQUEST_NO` BIGINT NOT NULL,
	`ATTENDANCE_REQUEST_NO` BIGINT NOT NULL,
	`PROJECT_NO` BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS `CHAT_ROOM` (
	`CHAT_ROOM_NO`	BIGINT	NOT NULL,
	`CHAT_ROOM_NAME`	VARCHAR(50)	NOT NULL,
	`CHAT_ROOM_TYPE`	VARCHAR(30)	NULL	COMMENT '전체 / 프로젝트 / 개인',
	`CHAT_ROOM_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`CHAT_ROOM_UPDATED_AT`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`CHAT_ROOM_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT '채팅방 유지 / 채팅방 삭제'
);

CREATE TABLE IF NOT EXISTS `CHAT_MESSAGE` (
	`CHAT_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`CHAT_ROOM_NO`	BIGINT	NOT NULL,
	`CHAT_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT '보임/삭제',
	`CHAT_MESSAGE`	VARCHAR(500)	NOT NULL,
	`CHAT_MESSAGE_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`CHAT_MESSAGE_UPDATED_AT`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`CHAT_MESSAGE_TYPE`	VARCHAR(10)	NOT NULL	COMMENT 'message / image / file',
	`ATTACHMENT_URL`	VARCHAR(1000)	NULL
);

CREATE TABLE IF NOT EXISTS `CHAT_ROOM_MEMBER` (
	`CHAT_ROOM_MEMBER_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`CHAT_ROOM_NO`	BIGINT	NOT NULL,
	`CHAT_ROOM_MEMBER_JOINED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '채팅방 참여 일시',
	`LAST_READ_CHAT_NO`	BIGINT	NULL	COMMENT '마지막까지 읽은 채팅 번호'
);

CREATE TABLE IF NOT EXISTS `REFRESH_TOKEN` (
	`REFRESH_TOKEN_ID`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`REFRESH_TOKEN_HASH`	VARCHAR(64)	NOT NULL	COMMENT 'UNIQUE',
	`REFRESH_TOKEN_FAMILY`	VARCHAR(36)	NOT NULL,
	`REFRESH_TOKEN_EXPIRES_AT`	DATETIME	NOT NULL,
	`REFRESH_TOKEN_IS_REVOKED`	VARCHAR(1)	NOT NULL	DEFAULT 'F'	COMMENT 'T / F (강제차단 / 로그아웃)',
	`REFRESH_TOKEN_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`REFRESH_TOKEN_UPDATED_AT`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`REFRESH_TOKEN_LAST_USED_AT`	DATETIME	NULL
);

CREATE TABLE IF NOT EXISTS `INQUIRY` (
	`INQUIRY_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`INQUIRY_TYPE`	VARCHAR(20)	NOT NULL,
	`INQUIRY_TITLE`	VARCHAR(200)	NOT NULL,
	`INQUIRY_CONTENT`	VARCHAR(500)	NOT NULL,
	`INQUIRY_STATUS`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT '처리중 / 완료',
	`DEVELOPER_EMAIL`	VARCHAR(100)	NOT NULL,
	`ATTACHMENT_URLS`	VARCHAR(2000)	NULL,
	`INQUIRY_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`INQUIRY_UPDATED_AT`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================
-- 2단계: 기본키 제약조건 추가
-- ============================================
ALTER TABLE `AGENCY` ADD CONSTRAINT `PK_AGENCY` PRIMARY KEY (`AGENCY_NO`);
ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (`MEMBER_NO`);
ALTER TABLE `PROJECT` ADD CONSTRAINT `PK_PROJECT` PRIMARY KEY (`PROJECT_NO`);
ALTER TABLE `HEALTH_SURVEY` ADD CONSTRAINT `PK_HEALTH_SURVEY` PRIMARY KEY (`HEALTH_SURVEY_NO`);
ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `PK_NOTIFICATION` PRIMARY KEY (`NOTIFICATION_NO`);
ALTER TABLE `LEAVE_BALANCE` ADD CONSTRAINT `PK_LEAVE_BALANCE` PRIMARY KEY (`LEAVE_BALANCE_NO`);
ALTER TABLE `ATTENDANCE_REQUEST` ADD CONSTRAINT `PK_ATTENDANCE_REQUEST` PRIMARY KEY (`ATTENDANCE_REQUEST_NO`);
ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `PK_ATTENDANCE` PRIMARY KEY (`ATTENDANCE_NO`);
ALTER TABLE `PROJECT_MEMBER` ADD CONSTRAINT `PK_PROJECT_MEMBER` PRIMARY KEY (`PROJECT_MEMBER_NO`);
ALTER TABLE `KANBAN_BOARD` ADD CONSTRAINT `PK_KANBAN_BOARD` PRIMARY KEY (`KANBAN_BOARD_NO`);
ALTER TABLE `KANBAN_CARD` ADD CONSTRAINT `PK_KANBAN_CARD` PRIMARY KEY (`KANBAN_CARD_NO`);
ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (`COMMENT_NO`);
ALTER TABLE `MEMO` ADD CONSTRAINT `PK_MEMO` PRIMARY KEY (`MEMO_NO`);
ALTER TABLE `HEALTH_SURVEY_QUESTION` ADD CONSTRAINT `PK_HEALTH_SURVEY_QUESTION` PRIMARY KEY (`HEALTH_SURVEY_QUESTION_NO`);
ALTER TABLE `HEALTH_SURVEY_RESPONSE_ITEM` ADD CONSTRAINT `PK_HEALTH_SURVEY_RESPONSE_ITEM` PRIMARY KEY (`HEALTH_SURVEY_RESPONSE_ITEM_NO`);
ALTER TABLE `DAILY_HEALTH_CHECK` ADD CONSTRAINT `PK_DAILY_HEALTH_CHECK` PRIMARY KEY (`HEALTH_CHECK_NO`);
ALTER TABLE `LEAVE_HISTORY` ADD CONSTRAINT `PK_LEAVE_HISTORY` PRIMARY KEY (`LEAVE_HISTORY_NO`);
ALTER TABLE `NEW_REQUEST` ADD CONSTRAINT `PK_NEW_REQUEST` PRIMARY KEY (`NEW_REQUEST_NO`);
ALTER TABLE `MANAGER` ADD CONSTRAINT `PK_MANAGER` PRIMARY KEY (`MANAGER_NO`);
ALTER TABLE `ARTIST_ASSIGNMENT` ADD CONSTRAINT `PK_ARTIST_ASSIGNMENT` PRIMARY KEY (`ARTIST_ASSIGNMENT_NO`);
ALTER TABLE `PROJECT_LEAVE_REQUEST` ADD CONSTRAINT `PK_PROJECT_LEAVE_REQUEST` PRIMARY KEY (`PROJECT_LEAVE_REQUEST_NO`);
ALTER TABLE `CHAT_ROOM` ADD CONSTRAINT `PK_CHAT_ROOM` PRIMARY KEY (`CHAT_ROOM_NO`);
ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `PK_CHAT_MESSAGE` PRIMARY KEY (`CHAT_NO`);
ALTER TABLE `CHAT_ROOM_MEMBER` ADD CONSTRAINT `PK_CHAT_ROOM_MEMBER` PRIMARY KEY (`CHAT_ROOM_MEMBER_NO`);
ALTER TABLE `REFRESH_TOKEN` ADD CONSTRAINT `PK_REFRESH_TOKEN` PRIMARY KEY (`REFRESH_TOKEN_ID`);
ALTER TABLE `INQUIRY` ADD CONSTRAINT `PK_INQUIRY` PRIMARY KEY (`INQUIRY_NO`);

-- ============================================
-- 3단계: AUTO_INCREMENT 적용 (외래키 추가 전에!)
-- ============================================
ALTER TABLE `AGENCY` MODIFY `AGENCY_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `MEMBER` MODIFY `MEMBER_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `PROJECT` MODIFY `PROJECT_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `HEALTH_SURVEY` MODIFY `HEALTH_SURVEY_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `NOTIFICATION` MODIFY `NOTIFICATION_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `LEAVE_BALANCE` MODIFY `LEAVE_BALANCE_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `ATTENDANCE_REQUEST` MODIFY `ATTENDANCE_REQUEST_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `ATTENDANCE` MODIFY `ATTENDANCE_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `PROJECT_MEMBER` MODIFY `PROJECT_MEMBER_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `KANBAN_BOARD` MODIFY `KANBAN_BOARD_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `KANBAN_CARD` MODIFY `KANBAN_CARD_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `COMMENT` MODIFY `COMMENT_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `MEMO` MODIFY `MEMO_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `HEALTH_SURVEY_QUESTION` MODIFY `HEALTH_SURVEY_QUESTION_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `HEALTH_SURVEY_RESPONSE_ITEM` MODIFY `HEALTH_SURVEY_RESPONSE_ITEM_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `DAILY_HEALTH_CHECK` MODIFY `HEALTH_CHECK_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `LEAVE_HISTORY` MODIFY `LEAVE_HISTORY_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `NEW_REQUEST` MODIFY `NEW_REQUEST_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `MANAGER` MODIFY `MANAGER_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `ARTIST_ASSIGNMENT` MODIFY `ARTIST_ASSIGNMENT_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `PROJECT_LEAVE_REQUEST` MODIFY `PROJECT_LEAVE_REQUEST_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `CHAT_ROOM` MODIFY `CHAT_ROOM_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `CHAT_MESSAGE` MODIFY `CHAT_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `CHAT_ROOM_MEMBER` MODIFY `CHAT_ROOM_MEMBER_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `REFRESH_TOKEN` MODIFY `REFRESH_TOKEN_ID` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `INQUIRY` MODIFY `INQUIRY_NO` BIGINT NOT NULL AUTO_INCREMENT;

-- ============================================
-- 4단계: UNIQUE 제약조건 추가
-- ============================================
-- AGENCY 관련
ALTER TABLE `AGENCY` ADD CONSTRAINT `UK_AGENCY_NAME` UNIQUE (`AGENCY_NAME`);
ALTER TABLE `AGENCY` ADD CONSTRAINT `UK_AGENCY_CODE` UNIQUE (`AGENCY_CODE`);

-- MEMBER 관련
ALTER TABLE `MEMBER` ADD CONSTRAINT `UK_MEMBER_EMAIL` UNIQUE (`MEMBER_EMAIL`);

-- MANAGER 관련
ALTER TABLE `ARTIST_ASSIGNMENT` ADD CONSTRAINT `UK_MANAGER_ARTIST` UNIQUE (`MANAGER_NO`, `ARTIST_MEMBER_NO`);

-- PROJECT_LEAVE_REQUEST 관련
ALTER TABLE `PROJECT_LEAVE_REQUEST` ADD CONSTRAINT `UK_ATTENDANCE_REQUEST_PROJECT` UNIQUE (`ATTENDANCE_REQUEST_NO`);

-- REFRESH_TOKEN 관련
ALTER TABLE `REFRESH_TOKEN` ADD CONSTRAINT `UK_REFRESH_TOKEN_HASH` UNIQUE (`REFRESH_TOKEN_HASH`);

-- ============================================
-- 5단계: 외래키 제약조건 추가 (AUTO_INCREMENT 적용 후)
-- ============================================
-- AGENCY 관련
ALTER TABLE `HEALTH_SURVEY` ADD CONSTRAINT `FK_HEALTH_SURVEY_AGENCY` FOREIGN KEY (`AGENCY_NO`) REFERENCES `AGENCY`(`AGENCY_NO`);
ALTER TABLE `MEMBER` ADD CONSTRAINT `FK_MEMBER_AGENCY` FOREIGN KEY (`AGENCY_NO`) REFERENCES `AGENCY`(`AGENCY_NO`);
ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_ATTENDANCE_AGENCY` FOREIGN KEY (`AGENCY_NO`) REFERENCES `AGENCY`(`AGENCY_NO`);
ALTER TABLE `NEW_REQUEST` ADD CONSTRAINT `FK_NEW_REQUEST_AGENCY` FOREIGN KEY (`AGENCY_NO`) REFERENCES `AGENCY`(`AGENCY_NO`);

-- MEMBER 관련
ALTER TABLE `PROJECT_MEMBER` ADD CONSTRAINT `FK_PROJECT_MEMBER_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `FK_NOTIFICATION_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `LEAVE_BALANCE` ADD CONSTRAINT `FK_LEAVE_BALANCE_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `ATTENDANCE_REQUEST` ADD CONSTRAINT `FK_ATTENDANCE_REQUEST_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `MEMO` ADD CONSTRAINT `FK_MEMO_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `HEALTH_SURVEY_RESPONSE_ITEM` ADD CONSTRAINT `FK_HEALTH_SURVEY_RESPONSE_ITEM_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_ATTENDANCE_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `DAILY_HEALTH_CHECK` ADD CONSTRAINT `FK_DAILY_HEALTH_CHECK_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `LEAVE_HISTORY` ADD CONSTRAINT `FK_LEAVE_HISTORY_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `NEW_REQUEST` ADD CONSTRAINT `FK_NEW_REQUEST_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `ARTIST_ASSIGNMENT` ADD CONSTRAINT `FK_ARTIST_ASSIGNMENT_ARTIST` FOREIGN KEY (`ARTIST_MEMBER_NO`) REFERENCES `MEMBER` (`MEMBER_NO`);
ALTER TABLE `MANAGER` ADD CONSTRAINT `FK_MANAGER_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER` (`MEMBER_NO`);
ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_COMMENT_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER` (`MEMBER_NO`);
ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `FK_CHAT_MESSAGE_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER` (`MEMBER_NO`);
ALTER TABLE `CHAT_ROOM_MEMBER` ADD CONSTRAINT `FK_CHAT_ROOM_MEMBER_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER` (`MEMBER_NO`);
ALTER TABLE `REFRESH_TOKEN` ADD CONSTRAINT `FK_REFRESH_TOKEN_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER` (`MEMBER_NO`);
ALTER TABLE `INQUIRY` ADD CONSTRAINT `FK_INQUIRY_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);

-- PROJECT 관련
ALTER TABLE `KANBAN_BOARD` ADD CONSTRAINT `FK_KANBAN_BOARD_PROJECT` FOREIGN KEY (`PROJECT_NO`) REFERENCES `PROJECT`(`PROJECT_NO`);
ALTER TABLE `PROJECT_MEMBER` ADD CONSTRAINT `FK_PROJECT_MEMBER_PROJECT` FOREIGN KEY (`PROJECT_NO`) REFERENCES `PROJECT`(`PROJECT_NO`);
ALTER TABLE `PROJECT_LEAVE_REQUEST` ADD CONSTRAINT `FK_PROJECT_LEAVE_REQUEST_PROJECT` FOREIGN KEY (`PROJECT_NO`) REFERENCES `PROJECT`(`PROJECT_NO`);

-- CHAT_ROOM 관련
ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `FK_CHAT_MESSAGE_CHAT_ROOM` FOREIGN KEY (`CHAT_ROOM_NO`) REFERENCES `CHAT_ROOM`(`CHAT_ROOM_NO`);
ALTER TABLE `CHAT_ROOM_MEMBER` ADD CONSTRAINT `FK_CHAT_ROOM_MEMBER_CHAT_ROOM` FOREIGN KEY (`CHAT_ROOM_NO`) REFERENCES `CHAT_ROOM`(`CHAT_ROOM_NO`);

-- KANBAN_BOARD 관련
ALTER TABLE `KANBAN_CARD` ADD CONSTRAINT `FK_KANBAN_CARD_BOARD` FOREIGN KEY (`BOARD_NO`) REFERENCES `KANBAN_BOARD`(`KANBAN_BOARD_NO`);

-- PROJECT_MEMBER 관련
ALTER TABLE `KANBAN_CARD` ADD CONSTRAINT `FK_KANBAN_CARD_PROJECT_MEMBER` FOREIGN KEY (`PROJECT_MEMBER_NO`) REFERENCES `PROJECT_MEMBER`(`PROJECT_MEMBER_NO`);

-- KANBAN_CARD 관련
ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_COMMENT_CARD` FOREIGN KEY (`KANBAN_CARD_NO`) REFERENCES `KANBAN_CARD`(`KANBAN_CARD_NO`);

-- HEALTH_SURVEY_QUESTION 관련
ALTER TABLE `HEALTH_SURVEY_RESPONSE_ITEM` ADD CONSTRAINT `FK_HEALTH_SURVEY_RESPONSE_ITEM_QUESTION` FOREIGN KEY (`HEALTH_SURVEY_QUESTION_NO`) REFERENCES `HEALTH_SURVEY_QUESTION`(`HEALTH_SURVEY_QUESTION_NO`);

-- MANAGER 관련
ALTER TABLE `ARTIST_ASSIGNMENT` ADD CONSTRAINT `FK_ARTIST_ASSIGNMENT_MANAGER` FOREIGN KEY (`MANAGER_NO`) REFERENCES `MANAGER` (`MANAGER_NO`);

-- ATTENDANCE_REQUEST 관련
ALTER TABLE `PROJECT_LEAVE_REQUEST` ADD CONSTRAINT `FK_PROJECT_LEAVE_REQUEST_ATTENDANCE_REQUEST` FOREIGN KEY (`ATTENDANCE_REQUEST_NO`) REFERENCES `ATTENDANCE_REQUEST`(`ATTENDANCE_REQUEST_NO`);