CREATE TABLE `KANBAN_CARD` (
	`KANBAN_CARD_NO`	BIGINT	NOT NULL,
	`BOARD_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_NAME`	VARCHAR(50)	NOT NULL,
	`KANBAN_CARD_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT N	COMMENT '완료/미완료 체크(Y/N)',
	`KANBAN_CARD_CREATED_AT`	DATETIME	NOT NULL	DEFAULT NOW,
	`KANBAN_CARD_UPDATED_AT`	DATETIME	NULL	DEFAULT NOW,
	`PROJECT_MEMBER_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_STARTED_AT`	DATE	NULL,
	`KANBAN_CARD_ENDED_AT`	DATE	NULL
);

CREATE TABLE `DAILY_HEALTH_CHECK` (
	`HEALTH_CHECK_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`HEALTH_CONDITION`	VARCHAR(20)	NULL,
	`SLEEP_HOURS`	INT	NULL,
	`DISCOMFORT_LEVEL`	INT	NULL,
	`HEALTH_CHECK_NOTES`	VARCHAR(1000)	NULL,
	`HEALTH_CHECK_CREATED_AT`	DATETIME	NULL	DEFAULT NOW
);

CREATE TABLE `MEMO` (
	`MEMO_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`CALENDAR_EVENT_NO`	BIGINT	NOT NULL,
	`MEMO_NAME`	VARCHAR(30)	NOT NULL,
	`MEMO_TEXT`	VARCHAR(255)	NULL,
	`MEMO_CREATED_AT`	DATETIME	NOT NULL,
	`MEMO_UPDATED_AT`	DATETIME	NULL,
	`MEMO_TYPE`	VARCHAR(12)	NULL	COMMENT '개인메모/캘린더메모'
);

CREATE TABLE `HEALTH_SURVEY_QUESTION` (
	`HEALTH_SURVEY_QUESTION_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_ORDER`	INT	NULL,
	`HEALTH_SURVEY_QUESTION_CONTENT`	VARCHAR(1000)	NULL,
	`HEALTH_SURVEY_QUESTION_MIN_SCORE`	INT	NULL,
	`HEALTH_SURVEY_QUESTION_MAX_SCORE`	INT	NULL,
	`HEALTH_SURVEY_QUESTION_CREATED_AT`	DATETIME	NOT NULL,
	`HEALTH_SURVEY_QUESTION_UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `NEW_REQUEST` (
	`NEW_REQUEST_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`NEW_REQUEST_DATE`	DATETIME	NULL,
	`NEW_REQUEST_STATUS`	VARCHAR(10)	NULL	COMMENT '승인/대기/거절'
);

CREATE TABLE `LEAVE_BALANCE` (
	`LEAVE_BALANCE_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`LEAVE_TYPE`	VARCHAR(20)	NOT NULL	DEFAULT 'ANNUAL'	COMMENT '연차 / 대체휴무 / 특별휴가',
	`LEAVE_BALANCE_TOTAL_DAYS`	INT	NOT NULL,
	`LEAVE_BALANCE_USED_DAYS`	INT	NULL	DEFAULT 0,
	`LEAVE_BALANCE_REMAIN_DAYS`	INT	NULL,
	`LEAVE_BALANCE_YEAR`	VARCHAR(4)	NOT NULL,
	`LEAVE_BALANCE_UPDATED_AT`	DATE	NULL
);

CREATE TABLE `AGENCY` (
	`AGENCY_NO`	BIGINT	NOT NULL,
	`AGENCY_NAME`	VARCHAR(30)	NULL,
	`AGENCY_CODE`	VARCHAR(6)	NULL,
	`AGENCY_LEAVE`	INT	NULL	DEFAULT 15
);

CREATE TABLE `HEALTH_SURVEY_RESPONSE` (
	`HEALTH_SURVEY_RESPONSE_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_RESPONSE_TOTAL_SCORE`	INT	NULL,
	`HEALTH_SURVEY_RESPONSE_STATUS`	VARCHAR(1)	NOT NULL	COMMENT '완료 / 미완료 (Y / N)',
	`HEALTH_SURVEY_RESPONSE_CREATED_AT`	DATETIME	NULL	DEFAULT NOW
);

CREATE TABLE `NOTIFICATION` (
	`NOTIFICATION_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`NOTIFICATION_NAME`	VARCHAR(30)	NULL,
	`NOTIFICATION_TEXT`	VARCHAR(260)	NULL,
	`NOTIFICATION_CREATED_AT`	DATETIME	NULL,
	`NOTIFICATION_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y	COMMENT 'Y / N',
	`NOTIFICATION_TYPE`	VARCHAR(10)	NULL
);

CREATE TABLE `MEMBER` (
	`MEMBER_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NULL,
	`MEMBER_NAME`	VARCHAR(20)	NOT NULL,
	`MEMBER_PASSWORD`	VARCHAR(100)	NOT NULL,
	`MEMBER_EMAIL`	VARCHAR(50)	NOT NULL	COMMENT 'UNIQUE',
	`MEMBER_PHONE`	VARCHAR(15)	NOT NULL,
	`MEMBER_STATUS`	VARCHAR(20)	NOT NULL	COMMENT '활성 / 휴면 (ACTIVE /  BLOCKED)',
	`MEMBER_PROFILE_IMAGE`	VARCHAR(100)	NULL,
	`MEMBER_PROFILE_BANNER_IMAGE`	VARCHAR(100)	NULL,
	`MEMBER_ROLE`	VARCHAR(100)	NOT NULL	COMMENT '웹툰 작가 / 웹소설 작가 / 어시스트 - 채색 / 어시스트 - 조명 / 어시스트 - 배경 / 어시스트 - 선화 / 어시스트- 기타 / 에이전시 관리자 / 담당자',
	`MEMBER_CREATED_AT`	DATETIME	NOT NULL	DEFAULT NOW,
	`MEMBER_UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `PROJECT` (
	`PROJECT_NO`	BIGINT	NOT NULL,
	`PROJECT_NAME`	VARCHAR(100)	NOT NULL,
	`PROJECT_STATUS`	VARCHAR(100)	NOT NULL	DEFAULT 연재	COMMENT '연재 / 휴재 / 완결',
	`PROJECT_COLOR`	VARCHAR(50)	NOT NULL	DEFAULT 기본색,
	`PROJECT_GENRE`	VARCHAR(50)	NULL,
	`PROJECT_CYCLE`	INT	NULL,
	`THUMBNAIL_FILE`	VARCHAR(500)	NULL,
	`PROJECT_STARTED_AT`	DATETIME	NULL
);

CREATE TABLE `ATTENDANCE_REQUEST` (
	`ATTENDANCE_REQUEST_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`ATTENDANCE_REQUEST_TYPE`	VARCHAR(20)	NOT NULL	COMMENT '연차 / 병가 / 워케이션 / 재택 / 휴재 / 반차 / 반반차',
	`ATTENDANCE_REQUEST_START_DATE`	DATETIME	NOT NULL,
	`ATTENDANCE_REQUEST_END_DATE`	DATETIME	NOT NULL,
	`ATTENDANCE_REQUEST_USING_DAYS`	INT	NOT NULL,
	`ATTENDANCE_REQUEST_REASON`	VARCHAR(255)	NULL,
	`WORKCATION_LOCATION`	VARCHAR(100)	NULL	COMMENT '워케이션 신청 시에만 작성',
	`MEDICAL_FILE_URL`	VARCHAR(500)	NOT NULL,
	`ATTENDANCE_REQUEST_STATUS`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT '신청 / 승인 / 반려 / 취소',
	`ATTENDANCE_REQUEST_REJECT_REASON`	VARCHAR(200)	NULL,
	`ATTENDANCE_REQUEST_CREATED_AT`	DATETIME	NOT NULL,
	`ATTENDANCE_REQUEST_UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `CALENDAR_EVENT` (
	`CALENDAR_EVENT_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`CALENDAR_EVENT_NAME`	VARCHAR(50)	NULL,
	`CALENDAR_EVENT_CONTENT`	VARCHAR(100)	NULL,
	`CALENDAR_EVENT_TYPE`	VARCHAR(20)	NULL,
	`CALENDAR_EVENT_STARTED_AT`	DATE	NOT NULL,
	`CALENDAR_EVENT_ENDED_AT`	DATE	NOT NULL,
	`CALENDAR_EVENT_CREATED_AT`	DATETIME	NOT NULL	DEFAULT NOW,
	`CALENDAR_EVENT_UPDATED_AT`	DATETIME	NULL	DEFAULT NOW,
	`CALENDAR_EVENT_COLOR`	VARCHAR(10)	NULL
);

CREATE TABLE `HEALTH_SURVEY` (
	`HEALTH_SURVEY_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_NAME`	VARCHAR(100)	NULL,
	`HEALTH_SURVEY_TYPE`	VARCHAR(30)	NULL	COMMENT '데일리/월간신체/월간정신',
	`HEALTH_SURVEY_CONTENT`	VARCHAR(30)	NULL,
	`HEALTH_SURVEY_STATUS`	VARCHAR(1)	NOT NULL	COMMENT '미검진 / 검진완료 ( Y / N )',
	`HEALTH_SURVEY_CREATED_AT`	DATETIME	NULL,
	`HEALTH_SURVEY_UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `KANBAN_BOARD` (
	`KANBAN_BOARD_NO`	BIGINT	NOT NULL,
	`PROJECT_NO`	BIGINT	NOT NULL,
	`KANBAN_BOARD_NAME`	VARCHAR(100)	NULL,
	`KANBAN_BOARD_ORDER`	INT	NOT NULL,
	`KANBAN_BOARD_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y	COMMENT 'Y / N'
);

CREATE TABLE `HEALTH_SURVEY_RESPONSE_ITEM` (
	`HEALTH_SURVEY_RESPONSE_ITEM_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_RESPONSE_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_QUESTION_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_QUESTION_ITEM_ANSWER_SCORE`	INT	NOT NULL	COMMENT '0 / 1 / 2 / 3',
	`HEALTH_SURVEY_QUESTION_ITEM_CREATED_AT`	DATETIME	NOT NULL
);

CREATE TABLE `ATTENDANCE` (
	`ATTENDANCE_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NOT NULL,
	`ATTENDANCE_TYPE`	VARCHAR(10)	NOT NULL	COMMENT ''출근', '퇴근'',
	`ATTENDANCE_TIME`	DATETIME	NOT NULL
);

CREATE TABLE `LEAVE_HISTORY` (
	`LEAVE_HISTORY_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`LEAVE_HISTORY_DATE`	DATETIME	NULL	DEFAULT NOW,
	`LEAVE_HISTORY_TYPE`	VARCHAR(30)	NOT NULL	COMMENT '경력 인정/ 징계 / 포상',
	`LEAVE_HISTORY_REASON`	VARCHAR(1000)	NULL,
	`LEAVE_HISTORY_AMOUNT`	INT	NOT NULL
);

CREATE TABLE `COMMENT` (
	`COMMENT_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_NO`	BIGINT	NOT NULL,
	`COMMENT_CONTENT`	VARCHAR(1000)	NULL
);

CREATE TABLE `TASK_HISTORY` (
	`TASK_HISTORY_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`BEFORE_TASK_HISTORY`	VARCHAR(1000)	NULL,
	`AFTER_TASK_HISTORY`	VARCHAR(1000)	NULL,
	`TASK_HISTORY_UPDATED_AT`	DATETIME	NULL	DEFAULT NOW
);

CREATE TABLE `PROJECT_MEMBER` (
	`PROJECT_MEMBER_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`PROJECT_NO`	BIGINT	NOT NULL,
	`PROJECT_MEMBER_ROLE`	VARCHAR(50)	NOT NULL	DEFAULT MEMBER	COMMENT 'LEADER / MEMBER'
);

ALTER TABLE `KANBAN_CARD` ADD CONSTRAINT `PK_KANBAN_CARD` PRIMARY KEY (
	`KANBAN_CARD_NO`
);

ALTER TABLE `DAILY_HEALTH_CHECK` ADD CONSTRAINT `PK_DAILY_HEALTH_CHECK` PRIMARY KEY (
	`HEALTH_CHECK_NO`
);

ALTER TABLE `MEMO` ADD CONSTRAINT `PK_MEMO` PRIMARY KEY (
	`MEMO_NO`
);

ALTER TABLE `HEALTH_SURVEY_QUESTION` ADD CONSTRAINT `PK_HEALTH_SURVEY_QUESTION` PRIMARY KEY (
	`HEALTH_SURVEY_QUESTION_NO`
);

ALTER TABLE `NEW_REQUEST` ADD CONSTRAINT `PK_NEW_REQUEST` PRIMARY KEY (
	`NEW_REQUEST_NO`
);

ALTER TABLE `LEAVE_BALANCE` ADD CONSTRAINT `PK_LEAVE_BALANCE` PRIMARY KEY (
	`LEAVE_BALANCE_NO`
);

ALTER TABLE `AGENCY` ADD CONSTRAINT `PK_AGENCY` PRIMARY KEY (
	`AGENCY_NO`
);

ALTER TABLE `HEALTH_SURVEY_RESPONSE` ADD CONSTRAINT `PK_HEALTH_SURVEY_RESPONSE` PRIMARY KEY (
	`HEALTH_SURVEY_RESPONSE_NO`
);

ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `PK_NOTIFICATION` PRIMARY KEY (
	`NOTIFICATION_NO`
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEMBER_NO`
);

ALTER TABLE `PROJECT` ADD CONSTRAINT `PK_PROJECT` PRIMARY KEY (
	`PROJECT_NO`
);

ALTER TABLE `ATTENDANCE_REQUEST` ADD CONSTRAINT `PK_ATTENDANCE_REQUEST` PRIMARY KEY (
	`ATTENDANCE_REQUEST_NO`
);

ALTER TABLE `CALENDAR_EVENT` ADD CONSTRAINT `PK_CALENDAR_EVENT` PRIMARY KEY (
	`CALENDAR_EVENT_NO`
);

ALTER TABLE `HEALTH_SURVEY` ADD CONSTRAINT `PK_HEALTH_SURVEY` PRIMARY KEY (
	`HEALTH_SURVEY_NO`
);

ALTER TABLE `KANBAN_BOARD` ADD CONSTRAINT `PK_KANBAN_BOARD` PRIMARY KEY (
	`KANBAN_BOARD_NO`
);

ALTER TABLE `HEALTH_SURVEY_RESPONSE_ITEM` ADD CONSTRAINT `PK_HEALTH_SURVEY_RESPONSE_ITEM` PRIMARY KEY (
	`HEALTH_SURVEY_RESPONSE_ITEM_NO`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `PK_ATTENDANCE` PRIMARY KEY (
	`ATTENDANCE_NO`
);

ALTER TABLE `LEAVE_HISTORY` ADD CONSTRAINT `PK_LEAVE_HISTORY` PRIMARY KEY (
	`LEAVE_HISTORY_NO`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`COMMENT_NO`
);

ALTER TABLE `TASK_HISTORY` ADD CONSTRAINT `PK_TASK_HISTORY` PRIMARY KEY (
	`TASK_HISTORY_NO`
);

ALTER TABLE `PROJECT_MEMBER` ADD CONSTRAINT `PK_PROJECT_MEMBER` PRIMARY KEY (
	`PROJECT_MEMBER_NO`
);

